### PR TITLE
Use SchemaCrawler commands for ChatGPT output

### PR DESCRIPTION
**Pull request by sualeh**

### CODE REVIEW

**Comment by adriens** [comment]
Hi @sualeh , what does this PR in termes of features ? I intend to make a demo this week-end and would like to be sure to show off features as much as I can :pray:

**Comment by sualeh** [comment]
The output will be literally the same as SchemaCrawler output, because it will call SchemaCrawler commands behind the scenes. I will add lint functionality soon also. If you can wait for one more weekend, you will have a better demo with lint.

**Comment by adriens** [comment]
> If you can wait for one more weekend, you will have a better demo with lint.

Sure I can, meanwhile I keep preparing chat sesion and post enhacements :+1:

**Comment by adriens** [comment]
Thanks for the release :muscle: :sunglasses:

**Pull request merged**
