### PR TITLE
Supported enumerated values as first class schema metadata

### PR DESCRIPTION
**Pull request by sualeh**
Fixes issue #284 - add support for PostgreSQL and MySQL enum values for columns, and outputs values in textual output and diagrams

### CODE REVIEW

**Comment by asindl** [comment]
I got excited to see the enums are now supported in PostGres.
From the command line, how would I ensure to see the enums in a html output? Anything I need to edit in the configs or in the commandline?

**Comment by sualeh** [comment]
@asindl - there is nothing special to do to see enum values in HTML output. It is supported out of the box.

**Comment by asindl** [comment]
@sualeh Well, tried it and it didn't work for me. 
Just to make sure: I have an enum in the DB like this:
`CREATE TYPE mySchema.myEnum AS ENUM
    ('value1', 'value2', 'value3', 'value4');`

So, that should work out of the box, right? But I can't see it in my html...

**Comment by sualeh** [comment]
@asindl - you also need to have a table with a column using this enum. The enum values will show up as constraints on the column.

**Comment by asindl** [comment]
@sualeh Hmmm, not for me. I basically do things like in the [PG documentation](https://www.postgresql.org/docs/9.1/datatype-enum.html) but running schemacrawler, I don't see the enum values in the documentation.

**Comment by sualeh** [comment]
@asindl  - if you don't have a table column using the enum, you will not see the values.

**Comment by asindl** [comment]
@sualeh I did as described in the PG documentation, like this:
`CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE TABLE person (
    name text,
    current_mood mood
);`
Is that what you describe 

> have a table column using the enum

Anything else needed?

**Comment by sualeh** [comment]
Yes, that is right. SchemaCrawler will describe the table columns correctly in the output. Please make sure that you are using the maximum info-level.

**Pull request merged**
