### PR TITLE
Fixes #1203 - add support for finding design issues with lint in ChatGPT integration

### LINKED ISSUE #1203: :point_up: Q&A with lints (chat with DbaGPT) :medal_sports:
### Feature Request

The idea here is to be able to get advices in a Q&A workflow about : 

- What does not look good according to lint rules
- What could/should be improved according to the lint engine

The chat could look like : 

- _"Can you tell me wha'ts going wrong with my database ?"_
- _"How could I improve my database design?"_
- _"Does my database pass the quality gate ?"_ (conditionnong schema acceptance... saving a lot of CI and DBA time)

### Possible Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sualeh**

### CODE REVIEW

**Comment by adriens** [comment]
:star_struck: ... what kind of prompt should I give ?:

> "Please give me the design issue on this database"

> "Pleas give me the design issue on this table"

**Comment by sualeh** [comment]
Yes, those will work.

**Comment by adriens** [comment]
I will work on shooting a live demo next week :muscle: :sunglasses:

**Comment by adriens** [comment]
:clap: :raised_hands: :partying_face:

**Pull request merged**
