### PR TITLE
Distribute DuckDB driver - fixes #1015

### LINKED ISSUE #1015: :memo: Write DEV.to > How to Visualize Your DuckDb Database with One Command (and Nothing to Install)
### Description

In the same way you wrote [How to Visualize Your SQLite Database with One Command (and Nothing to Install) ](https://dev.to/sualeh/how-to-visualize-your-sqlite-database-with-one-command-and-nothing-to-install-1f4m), could you use [DuckDb jdbc driver](https://duckdb.org/docs/api/java.html) to write a dedicated DEV.to article called _How to Visualize Your DuckDb Database with One Command (and Nothing to Install) _ ?

- [Java and DuckDB](https://duckdb.org/docs/api/java.html)
- [`jdbc` driver on Maven Central](https://search.maven.org/artifact/org.duckdb/duckdb_jdbc)
- Jdbc Classname : `org.duckdb.DuckDBDriver`
- Get a connection:

```java
ro_prop.setProperty("duckdb.read_only", "true");
Connection conn_ro = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database", ro_prop);
```

### How to Reproduce

_No response_

### Relevant log output

_No response_

### SchemaCrawler Version

latest

### Java Version

current LTS

### Operating System and Version

Docker

### Relational Database System and Version

DuckDb

### JDBC Driver and Version

current

### PR DESCRIPTION
**Pull request by sualeh**

### CODE REVIEW

**Comment by adriens** [comment]
[:bird: Tweet](https://twitter.com/rastadidi/status/1622342481844273152)

image

**Comment by adriens** [comment]
[ linkedIn](https://www.linkedin.com/posts/adrien-sales_distribute-duckdb-driver-fixes-1015-by-activity-7028108557610881024-_lBy?utm_source=share&utm_medium=member_desktop)

image

**Comment by adriens** [comment]
- https://github.com/duckdb/duckdb/issues/6781
- https://github.com/duckdb/duckdb/issues/6761
- https://github.com/duckdb/duckdb/issues/6767
- https://github.com/schemacrawler/SchemaCrawler/pull/1016

**Comment by adriens** [comment]
:bulb: Wil you share with us a "How to Visualize Your DuckDB Database with One Command (and Nothing to Install)" post like you did in [How to Visualize Your SQLite Database with One Command (and Nothing to Install)](https://dev.to/sualeh/how-to-visualize-your-sqlite-database-with-one-command-and-nothing-to-install-1f4m) :grey_question:

**Comment by sualeh** [comment]
> 💡 Wil you share with us a "How to Visualize Your DuckDB Database with One Command 

Yes, but only after DuckDB supports retrieval of foreign key metadata. Otherwise the diagram will not look good.

**Pull request merged**
